# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Категория', max_length=50, verbose_name='Категория')),
                ('boolVisible', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('metaDescription', models.CharField(default='Категория', max_length=50, verbose_name='meta Description')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
    ]
