# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Описание'),
        ),
    ]
