# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Услуга', max_length=50, verbose_name='Название услуги')),
                ('metaDescription', models.CharField(default='Категория', max_length=50, verbose_name='meta Description')),
                ('boolVisible', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('duration', models.CharField(default='от 1 до 99 недель', max_length=30, verbose_name='Сроки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
