# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Подкатегория', max_length=50, verbose_name='Подкатегория')),
                ('boolVisible', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('metaDescription', models.CharField(default='Категория', max_length=50, verbose_name='meta Description')),
                ('description', models.CharField(default='', max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Подкатегории',
                'verbose_name': 'Подкатегория',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.SubCategory'),
        ),
    ]
