# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170806_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Материал', max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name_plural': 'Материалы',
                'verbose_name': 'Материал',
            },
        ),
    ]
