# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.Material'),
        ),
    ]
