# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='boolShowOnMain',
            field=models.BooleanField(default=False, verbose_name='Публиковать вместе с категориями'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='boolShowOnMain',
            field=models.BooleanField(default=False, verbose_name='Публиковать вместе с категориями'),
        ),
    ]
