# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20170806_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='boolShowOnMain',
            field=models.BooleanField(default=False, verbose_name='Публиковать вместе с категориями'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Название категории/услуги', max_length=50, verbose_name='Название категории/услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='Название категории/услуги', max_length=50, verbose_name='Название категории/услуги'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='Название категории/услуги', max_length=50, verbose_name='Название категории/услуги'),
        ),
    ]
