# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стоимость проекта/м^2', max_length=50, verbose_name='Стоимость проекта/м^2')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Едицы измерения',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Стоимость от'),
        ),
        migrations.AlterField(
            model_name='service',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Material', verbose_name='Основной материал'),
        ),
        migrations.AddField(
            model_name='service',
            name='priceunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.PriceUnit', verbose_name='Единица измерения'),
        ),
    ]
