# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import good.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20170806_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=25)),
                ('image', models.ImageField(blank=True, default='', upload_to=good.models.make_upload_path, verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.SubCategory')),
            ],
        ),
    ]
