# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_imagessub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
