# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_remove_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagessub',
            old_name='project',
            new_name='category',
        ),
    ]
