# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import good.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20170812_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=good.models.make_upload_path, verbose_name='Картинка'),
        ),
    ]
