# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='Заголовок страницы!', max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='Заголовок страницы!', max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(default='Заголовок страницы!', max_length=50, verbose_name='Title'),
        ),
    ]
