# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20170911_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Заголовок страницы!', max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Заголовок страницы!', max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(default='Заголовок страницы!', max_length=80, verbose_name='Title'),
        ),
    ]
