# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import good.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=25)),
                ('image', models.ImageField(blank=True, default='', upload_to=good.models.make_upload_path, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название проекта', max_length=180, verbose_name='Название')),
                ('metadescription', models.CharField(default='def', max_length=180, verbose_name='meta description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='Описание', verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('ASD', models.CharField(max_length=5)),
                ('boolVisible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Project'),
        ),
    ]
