# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ASD',
        ),
        migrations.AlterField(
            model_name='project',
            name='boolVisible',
            field=models.BooleanField(default=False, verbose_name='Опублковать'),
        ),
        migrations.AlterField(
            model_name='project',
            name='metadescription',
            field=models.CharField(default='def', max_length=180, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
