# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import good.models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20170803_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=good.models.make_upload_path, verbose_name='Картинка'),
        ),
    ]
