# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Name', max_length=40, verbose_name='')),
                ('opinion', models.CharField(default='', max_length=150, verbose_name='')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка1')),
                ('boolVisible', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
            },
        ),
    ]
