# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import good.models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='image',
            field=models.ImageField(blank=True, upload_to=good.models.make_upload_path, verbose_name='Фото проекта'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='name',
            field=models.CharField(default='Name', max_length=40, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='opinion',
            field=models.CharField(default='', max_length=150, verbose_name='Отзыв'),
        ),
    ]
