# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0007_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='Ответ', verbose_name='Ответ'),
        ),
    ]
