# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0008_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='Напишите Ваш вопрос', verbose_name='Ваш вопрос'),
        ),
    ]
