# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0009_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='telephone',
            field=models.CharField(default='+7 (123) 456-7891', max_length=18, verbose_name='Телефон'),
        ),
    ]
