# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0010_auto_20170810_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=180, verbose_name='Title')),
                ('metaDescription', models.CharField(default='Title', max_length=180)),
                ('text', models.TextField(default=' ', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
