# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0011_aboutsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsite',
            name='url',
            field=models.CharField(default='aboutcompany', max_length=25, verbose_name='URL'),
        ),
    ]
