# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Услуга', max_length=25, verbose_name='Услуга')),
                ('text', models.CharField(default='Описание услуги', max_length=300, verbose_name='Описание услуги')),
                ('prop1', models.CharField(default='Свойство', max_length=20, verbose_name='Свойство 1')),
                ('prop2', models.CharField(default='Свойство', max_length=20, verbose_name='Свойство 2')),
                ('prop3', models.CharField(default='Свойство', max_length=20, verbose_name='Свойство 3')),
                ('prop4', models.CharField(default='Свойство', max_length=20, verbose_name='Свойство 4')),
                ('link', models.CharField(default='/', max_length=350, verbose_name='Ссылка')),
                ('boolVisible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
