# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20170807_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='prop1',
            field=models.CharField(default='Свойство', max_length=33, null=True, verbose_name='Свойство 1'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='prop2',
            field=models.CharField(default='Свойство', max_length=33, null=True, verbose_name='Свойство 2'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='prop3',
            field=models.CharField(default='Свойство', max_length=33, null=True, verbose_name='Свойство 3'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='prop4',
            field=models.CharField(default='Свойство', max_length=33, null=True, verbose_name='Свойство 4'),
        ),
    ]
