# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20170807_1211'),
        ('slider', '0004_auto_20170807_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='subcat',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='service.SubCategory'),
        ),
    ]
