# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_slide_subcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
        migrations.AlterField(
            model_name='slide',
            name='boolVisible',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subcat',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='service.SubCategory', verbose_name='Ссылка на услугу'),
        ),
    ]
